example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('wishlist/', include('wishlist.urls')),
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_ajax, name='show_ajax'),
    path('ajax/submit', create_wishlist, name='create_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
import datetime

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Dafi Nafidz Radhiyya',
        'last_login': request.COOKIES['last_login'].split('.')[0],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_ajax(request):
    context = {
        'nama': 'Dafi Nafidz Radhiyya',
        'last_login': request.COOKIES['last_login'].split('.')[0],
    }
    return render(request, "wishlist_ajax.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_ajax")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def create_wishlist(request):
    if request.method == 'POST':
        nama = request.POST.get('nama')
        harga = request.POST.get('harga')
        deskripsi = request.POST.get('deskripsi')

        # print(f"{nama = }\n{harga = }\n{deskripsi = }")
        new_wish = BarangWishlist(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
        new_wish.save()

        return HttpResponse(serializers.serialize("json", [new_wish]), content_type="application/json")
    return render(request, 'wishlist_ajax.html')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{% static 'letter-d.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dafi's Wishlist App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>

    <div class = "login">

        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn btn-primary" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block content %}  

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registrasi Akun</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>

      <div class = "login">
          
          <h1>Formulir Registrasi</h1>  
      
              <form method="POST" >  
                  {% csrf_token %}  
                  <table>  
                      {{ form.as_table }}  
                      <tr>  
                          <td></td>
                          <td><input type="submit" name="submit" value="Daftar"/></td>  
                      </tr>  
                  </table>  
              </form>
      
          {% if messages %}  
              <ul>   
                  {% for message in messages %}  
                      <li>{{ message }}</li>  
                      {% endfor %}  
              </ul>   
          {% endif %}
      
      </div>  
  </body>
</html>
{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand">
          <img src="https://cdn.discordapp.com/attachments/902951430153981993/1024916342211616778/letter-w_1.png" alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
          Wishlist
        </a>
        <h3>Selamat datang, {{nama}}!</h3>
        <a class="btn btn-outline-danger" href="{% url 'wishlist:logout' %}">Logout</a>
      </div>
    </nav>
    
  
    <div class="table-responsive-sm">
      <table class="table">
        <thead>
          <tr>
          <th>Nama Barang</th>
          <th>Harga Barang</th>
          <th>Deskripsi</th>
          </tr>
        </thead>
        <tbody>
          {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
          {% for barang in list_barang %}
              <tr>
                  <td>{{barang.nama_barang}}</td>
                  <td>{{barang.harga_barang}}</td>
                  <td>{{barang.deskripsi}}</td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <h5>Sesi terakhir login: {{ last_login }}</h5>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand">
          <img src="https://cdn.discordapp.com/attachments/902951430153981993/1024916342211616778/letter-w_1.png" alt="Logo" width="24" height="24" class="d-inline-block align-text-top">
          Wishlist
        </a>
        <h3>Selamat datang, {{nama}}!</h3>
        <a class="btn btn-outline-danger" href="{% url 'wishlist:logout' %}">Logout</a>
      </div>
    </nav>
    
  
    <div class="table-responsive-sm">
      <table class="table">
        <thead>
          <tr>
          <th>Nama Barang</th>
          <th>Harga Barang</th>
          <th>Deskripsi</th>
          </tr>
        </thead>
        <tbody id="table">
          {% comment %} Tambahkan data di bawah baris ini {% endcomment %}

        </tbody>
      </table>
    </div>
    <h5>Sesi terakhir login: {{ last_login }}</h5>

    <div class = "submit">
      
        <h3>Tambah Wishlist</h3>
    
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Nama Barang: </td>
                    <td><input type="text" id="nama" name="nama" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Harga Barang: </td>
                    <td><input type="text" id="harga" name="harga" class="form-control"></td>
                </tr>
    
                <tr>
                    <td>Deskripsi: </td>
                    <td><input type="text" id="deskripsi" name="deskripsi" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td>
                      <input class="btn btn-primary" id= "submit" type="submit" value="Submit">
                    </td>
                </tr>
            </table>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
    
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
      function showTable(data) {
        $("#table").empty();
        for (let i = 0; i < data.length; i++) {
          $("#table").append(`
              <tr>
                  <td>${data[i].fields.nama_barang}</td>
                  <td>${data[i].fields.harga_barang}</td>
                  <td>${data[i].fields.deskripsi}</td>
              </tr>`)
        }
      }

      function createWishlist(event) {
        event.preventDefault();
        $.post(
          "{% url 'wishlist:create_wishlist' %}",
          {
            nama: $("#nama").val(),
            harga: $("#harga").val(),
            deskripsi: $("#deskripsi").val(),
            csrfmiddlewaretoken: "{{ csrf_token }}"
          },
          function() {
            $.get("/wishlist/json", showTable)
          },
          "json"
        );
      }

      $(document).ready(function(){
        $("#submit").click(createWishlist);
        $.get("/wishlist/json", showTable);
      });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

{% endblock content %}